// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/content-sdk-go/config"
	layoutservice "github.com/content-sdk-go/layoutService"
	"github.com/content-sdk-go/models"
)

// EditingScripts renders client scripts and data for editing/preview mode for Pages.
// Renders script required for the Design Library (when mode is PageModeDesignLibrary).
// Returns an empty fragment if not in editing/preview mode.
func EditingScripts(page *models.Page, cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if page == nil || page.LayoutData == nil {
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if layoutData, ok := page.LayoutData.(*layoutservice.LayoutServiceData); ok {
				if shouldRenderEditingScripts(page, layoutData) {
					if isDesignLibraryMode(page, layoutData) {
						templ_7745c5c3_Err = renderDesignLibraryScript(cfg).Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = renderEditingScripts(layoutData).Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
				}
			}
		}
		return nil
	})
}

// shouldRenderEditingScripts determines if editing scripts should be rendered
func shouldRenderEditingScripts(page *models.Page, layoutData *layoutservice.LayoutServiceData) bool {
	// Don't render if in normal or preview mode
	if page.EditingContext != nil {
		mode := page.EditingContext.Mode
		if mode == models.PageModeNormal || mode == models.PageModePreview {
			return false
		}
	}

	// Check if page editing flag is set in context
	if layoutData.Sitecore.Context.PageEditing != nil && !*layoutData.Sitecore.Context.PageEditing {
		// Also check page state
		if layoutData.Sitecore.Context.PageState != nil {
			state := string(*layoutData.Sitecore.Context.PageState)
			return state == "edit" || state == "preview"
		}
		return false
	}

	return true
}

// isDesignLibraryMode determines if we're in Design Library mode
func isDesignLibraryMode(page *models.Page, layoutData *layoutservice.LayoutServiceData) bool {
	// Check page mode first
	if page.EditingContext != nil && page.EditingContext.Mode == models.PageModeDesignLibrary {
		return true
	}

	// Check rendering type
	if layoutData.Sitecore.Context.RenderingType != nil {
		return *layoutData.Sitecore.Context.RenderingType == layoutservice.RenderingTypeComponent
	}

	return false
}

// renderDesignLibraryScript renders the Design Library script with cache buster
func renderDesignLibraryScript(cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if scriptURL := getDesignLibraryScriptURLWithCacheBuster(cfg); scriptURL != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(scriptURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editing_scripts.templ`, Line: 75, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" suppressHydration></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// getDesignLibraryScriptURLWithCacheBuster returns the Design Library script URL with cache buster
func getDesignLibraryScriptURLWithCacheBuster(cfg *config.Config) string {
	if cfg == nil {
		return ""
	}

	now := time.Now().UTC()
	hour := fmt.Sprintf("%02d", now.Hour())
	day := fmt.Sprintf("%02d", now.Day())
	month := fmt.Sprintf("%02d", int(now.Month()))
	year := fmt.Sprintf("%d", now.Year())
	cacheTimestamp := fmt.Sprintf("%s-%s-%s-%s", hour, day, month, year)

	baseURL := cfg.GetDesignLibraryScriptURL()
	return fmt.Sprintf("%s?cb=%s", baseURL, cacheTimestamp)
}

// renderEditingScripts renders client scripts and client data for editing mode
func renderEditingScripts(layoutData *layoutservice.LayoutServiceData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(layoutData.Sitecore.Context.ClientScripts) > 0 {
			for _, src := range layoutData.Sitecore.Context.ClientScripts {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<script src=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(src)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editing_scripts.templ`, Line: 101, Col: 20}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"></script>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		if layoutData.Sitecore.Context.ClientData != nil {
			if clientDataMap, ok := layoutData.Sitecore.Context.ClientData.(map[string]any); ok {
				for id, data := range clientDataMap {
					templ_7745c5c3_Err = renderClientDataScriptTag(id, data).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
		}
		return nil
	})
}

// renderClientDataScriptTag renders a single client data script tag using Raw HTML
func renderClientDataScriptTag(id string, data any) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(buildClientDataScriptHTML(id, data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// buildClientDataScriptHTML builds the complete script tag HTML with JSON data
func buildClientDataScriptHTML(id string, data any) string {
	jsonData, err := json.Marshal(data)
	if err != nil {
		return ""
	}
	return fmt.Sprintf(`<script id="%s" type="application/json">%s</script>`, id, string(jsonData))
}

var _ = templruntime.GeneratedTemplate
